apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "ekstern-trekk-api"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  maskinporten:
    enabled: true
    scopes:
      exposes:
        # nav:utbetaling/trekkopplysning/innmelding
        - enabled: true
          product: "utbetaling"
          separator: "/"
          name: "trekkopplysning/innmelding"
          consumers:
            - orgno: "123456789"
  webproxy: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: "1000m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"
  ingresses:
    - "https://ekstern-trekk-api.ekstern.dev.nav.no"
    - "https://ekstern-trekk-api.intern.dev.nav.no"
  envFrom:
    - secret: ekstern-trekk-api-secret
    - configmap: ekstern-trekk-api-config
  kafka:
    pool: nav-dev
  accessPolicy:
    outbound:
      external:
        - host: b27apvl222.preprod.local
          ports:
            - port: 1413
  gcp:
    sqlInstances:
      - type: POSTGRES_18
        name: ekstern-trekk-api-db
        databases:
          - name: ekstern-trekk-api-db
            envVarPrefix: POSTGRES
        diskAutoresize: false
        diskType: SSD
        tier: db-f1-micro
  env:
    - name: EMOTTAK_LOGGING_LEVEL
      value: DEBUG
    - name: TREKKOPPL_MQ_HOST
      value: "mqls04.preprod.local"
    - name: TREKKOPPL_MQ_PORT
      value: "1413"
    - name: TREKKOPPL_MQ_QMGR
      value: "MQLS04"
    - name: TREKKOPPL_MQ_CHANNEL
      value: "Q1_EMOTTAK_ASYNCH"
    - name: TREKKOPPL_MQ_QUEUE
      value: "QA.Q1_231.OB04_INNRAPP_TREKK"
