server {
  port = 8080
  preWait = "5s"
}

database {
  jdbcUrl = "${POSTGRES_JDBC_URL:-}"
  jdbcUser = "${POSTGRES_USER:-}"
  jdbcPassword = "${POSTGRES_PASSWORD:-}"
  maxConnectionPoolSizeForUser = "4"
  maxConnectionPoolSizeForAdmin = "1"
  distinctValuesRefreshRateInHours = "24"
}

environment {
  naisClusterName = "${NAIS_CLUSTER_NAME:-local}"
}

kafka {
  bootstrapServers = "${KAFKA_BROKERS:-http://localhost:9092}"
  securityProtocol = "SSL"
  keystoreType = "PKCS12"
  keystoreLocation = "${KAFKA_KEYSTORE_PATH:-}"
  keystorePassword = "${KAFKA_CREDSTORE_PASSWORD:-}"
  truststoreType = "JKS"
  truststoreLocation = "${KAFKA_TRUSTSTORE_PATH:-}"
  truststorePassword = "${KAFKA_CREDSTORE_PASSWORD:-}"
  groupId = "ekstern-trekk-api"
}

kafkaResponseQueue {
  active = "${TREKKAPI_RESPONSE_QUEUE:-true}"
  topic = "team-emottak.trekkapi.respons"
  initOffset = "${RETRY_INIT_OFFSET:-latest}"
}

trekkopplysningmq {
  hostname = "${TREKKOPPL_MQ_HOST:-}"
  port = "${TREKKOPPL_MQ_PORT:-1413}"
  queueManager = "${TREKKOPPL_MQ_QMGR:-}"
  channel = "${TREKKOPPL_MQ_CHANNEL:-}"
  queue = "${TREKKOPPL_MQ_QUEUE:-}"
  username = "${TREKKOPPL_MQ_USERNAME:-}"
  password = "${TREKKOPPL_MQ_PASSWORD:-}"
}

