server {
  port = 8080
  preWait = "5s"
}

database {
  jdbcUrl = "${POSTGRES_JDBC_URL:-}"
  jdbcUser = "${POSTGRES_USER:-}"
  jdbcPassword = "${POSTGRES_PASSWORD:-}"
  maxConnectionPoolSizeForUser = "4"
  maxConnectionPoolSizeForAdmin = "1"
  distinctValuesRefreshRateInHours = "24"
}

environment {
  naisClusterName = "${NAIS_CLUSTER_NAME:-local}"
}

kafka {
  groupId = "ekstern-trekk-api"
}

kafkaResponseQueue {
  active = "${TREKKAPI_RESPONSE_QUEUE:-true}"
  topic = "team-emottak.trekkapi.response"
  initOffset = "${RETRY_INIT_OFFSET:-latest}"
}
