/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package no.nav.trekkapi

import arrow.continuations.SuspendApp
import arrow.continuations.ktor.server
import arrow.core.raise.result
import arrow.fx.coroutines.ResourceScope
import arrow.fx.coroutines.resourceScope
import io.ktor.server.netty.Netty
import io.micrometer.prometheus.PrometheusConfig
import io.micrometer.prometheus.PrometheusMeterRegistry
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.awaitCancellation
import kotlinx.coroutines.launch
import no.nav.trekkapi.configuration.config
import no.nav.trekkapi.innmelding.TrekkInnmeldingModel
import no.nav.trekkapi.innmelding.TrekkInnmeldingService
import no.nav.trekkapi.innmelding.startResponseReceiver
import no.nav.trekkapi.persistence.Database
import no.nav.trekkapi.persistence.TrekkInnmeldingRepository
import no.nav.trekkapi.util.coroutineScope
import org.slf4j.LoggerFactory

val log = LoggerFactory.getLogger("no.nav.emottak.ebms.async.LocalApp")

fun main(args: Array<String>) =
    SuspendApp {
        log.info("--- Starting LOCAL application")
        result {
            resourceScope {
                runServer()
                awaitCancellation()
            }
        }
    }

suspend fun ResourceScope.runServer() {
    /*
    This App is intended to run locally, using a Postgres DB and Kafka running in local containers (e.g. as started by RunLocalContainers).
    It is supposed to contain the same setup as the production App, with dummy services wherever needed for the current run/test.
    It has been used to test retry-logic, in this way:
    - start RunLocalContainers.main() in the IDE. Wait for local Kafka etc to be ready
    - start this App in the IDE. It should run according to its setup, using local DB and Kafka
    - run LocalTestClient.main() in the IDE, let it produce messages on local Kafka or whatever input you need for your test
     */

    // Use the config corresponding to Local containers
    val database = Database(getRunningPostgresConfiguration())
    println(" ************ Setting up to use local DB with URL: " + database.dataSource.jdbcUrl)

    val kafkaUrl = getRunningKafkaBrokerUrl()
    println(" ************ Setting up to use local Kafka with URL: " + kafkaUrl)
    System.setProperty("KAFKA_BROKERS", kafkaUrl)

    val config = config()
    println(" ************ config.kafkaResponseQueue.active: " + config.kafkaResponseQueue.active)

    println(" ************ Setting up services ")
    val trekkInnmeldingModel = TrekkInnmeldingModel()
    val trekkInnmeldingRepository = TrekkInnmeldingRepository(database)
    val mqConfig = config.trekkopplysningMq
    val trekkInnmeldingService = TrekkInnmeldingService(mqConfig, trekkInnmeldingRepository)

    println(" ************ Starting server ")
    val prometheusMeterRegistry = PrometheusMeterRegistry(PrometheusConfig.DEFAULT)
    val serverConfig = config.server
    server(
        factory = Netty,
        port = serverConfig.port.value,
        preWait = serverConfig.preWait,
        module = trekkapiModule(trekkInnmeldingService, prometheusMeterRegistry),
    )

    println(" ************ Starting response receiver ")
    log.info("Configuration: {}", config)
    if (config.kafkaResponseQueue.active) {
        log.info("Starting response receiver")
        val eventReceiverScope = coroutineScope(kotlin.coroutines.coroutineContext + Dispatchers.IO)
        eventReceiverScope.launch {
            startResponseReceiver(
                config.kafkaResponseQueue.topic,
                config.kafka.groupId,
                trekkInnmeldingModel,
                trekkInnmeldingRepository,
            )
        }
    }
}
