[versions]
kotest = "6.1.4"
ktor-test = "3.4.3"
testcontainers = "2.0.5"
mockk = "1.14.9"
mock-oauth2-server = "3.0.3"

[libraries]
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

ktor-server-test = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor-test" }

testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }
testcontainers-kafka = { module = "org.testcontainers:testcontainers-kafka", version.ref = "testcontainers" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

mock-oauth2-server = { module = "no.nav.security:mock-oauth2-server", version.ref = "mock-oauth2-server" }

[bundles]
kotest = ["kotest-runner", "kotest-assertions"]
